spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kfokam48}
    username: ${DB_USER:kfokam48}
    password: ${DB_PASSWORD:kfokam48}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080
